### PR TITLE
rename magical bitcoin to bitcoin dev kit

### PR DESCRIPTION
**Pull request by notmandatory**
Update
* icons
* logos
* github repo links

### CODE REVIEW

**Comment by notmandatory** [comment]
A couple open questions:

   1. do we still want to call the repl example app `magic` ? in the original site it was called `repl` in a couple places and then `magic` in the detailed instructions, either one is fine for me, I just want to be consistent
   1. does the logo image look ok? I added the rounded corners because the square version didn't look good, but I'm open to other ideas

still TODO:

  - [x] add the contributors page
  - [x] rename `magic` to `repl`
  - [x] after moving `magical-bitcoin-wallet` to `bdk` update Cargo and retest all `repl` instructions 
  - [x] prior to publishing deactivate the current bitcoindevkit.org site and change the CNAME file in this PR to `bitcoinddevkit.org`

**Comment by afilini** [comment]
>     1. do we still want to call the repl example app `magic` ? in the original site it was called `repl` in a couple places and then `magic` in the detailed instructions, either one is fine for me, I just want to be consistent

They are both valid names currently, there are two examples in `Cargo.toml` that point to the same file. Cargo actually doesn't really like this and gives a warning when the project is compiled.

I would probably go back to just calling it `repl`, since over time it's becoming less and less a fully working wallet and just more of a useful debugging tools for developers working on the library.

Maybe in the future we could make an external project called something like `magical-cli` with the goal of actually making a usable (albeit cli-only) wallet. For now I would just stick with `repl` and remove the double example from the `Cargo.toml` in the main repo to fix the warning.

>     2. does the logo image look ok? I added the rounded corners because the square version didn't look good, but I'm open to other ideas

I personally really like it! I would also use the same (or a similar) logo for Twitter, the current profile picture looks very low resolution, at least on my phone.

**Comment by afilini** [comment]
Also another TODO:

- [ ] replace the generated doc for `magical` with the one for `bdk` in /static/docs-rs

I usually generate it with:

```
cargo +nightly rustdoc --features=compiler,electrum,esplora,compact_filters,key-value-db -- --cfg docsrs
```

**Comment by notmandatory** [comment]
hope it's OK but I made a new bitcoindevkit/bitcoindevkit.org repo and pushed the branch for this PR to it. My thinking is  since we want to keep the magicalbitcoin.org site for example apps we should not merge this PR and I should close it. We can do other PRs to update the magicalbitcoin.org site for it's new purpose.

**Comment by afilini** [comment]
makes sense, I'll close this pr then

**Pull request closed without merging**
